version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: primakov
      POSTGRES_PASSWORD: primakov
      POSTGRES_DB: primakovapp
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
